In [22]:
import pandas as pd

df_rev=pd.read_csv('/home/mihnearad/Development/BankingInfo-Parse-Script/.data/REVBUS.csv')

In [23]:
df_rev.head()

,Date started (UTC),Date completed (UTC),ID,Type,State,Description,Reference,Payer,Card number,Card label,...,Fee currency,Balance,Account,Beneficiary account number,Beneficiary sort code or routing number,Beneficiary IBAN,Beneficiary BIC,MCC,Related transaction id,Spend program
0,2024-08-04,2024-08-05,66af8489-e3e7-a8d0-8d09-251cedc0feda,CARD_PAYMENT,COMPLETED,Www.orange.ro Contul-m,NaN,Mihnea Radulescu,516760******5470,Virtual,...,RON,531.72,RON Main,NaN,NaN,NaN,NaN,4814.0,NaN,NaN
1,2024-08-05,2024-08-05,66b093aa-6026-a23a-8a8a-6cbf917962fb,TRANSFER,COMPLETED,To Mihnea Radulescu,Diurna,Mihnea Radulescu,NaN,NaN,...,EUR,5.29,EUR Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-08-04,2024-08-05,66afa537-569a-a173-a088-09ec50247d56,CARD_PAYMENT,COMPLETED,Lidl Ro 0336,NaN,Mihnea Radulescu,516760******7588,Standard,...,RON,744.37,RON Main,NaN,NaN,NaN,NaN,5411.0,NaN,NaN
3,2024-07-27,2024-07-27,66a4dfb6-e5cd-aeea-92d3-92bc7c6bb5f4,TRANSFER,COMPLETED,To Mihnea Radulescu,Diurna,Mihnea Radulescu,NaN,NaN,...,EUR,35.29,EUR Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-07-27,2024-07-27,66a4df99-ea5d-a72d-9770-80e2f3fff75f,TRANSFER,COMPLETED,To Mihnea Radulescu,Diurna,Mihnea Radulescu,NaN,NaN,...,EUR,105.29,EUR Main,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
new_order_column=['Date started (UTC)','Description','Reference','Amount','Fee currency']

df_rev=df_rev[new_order_column]
df_rev.head()

  Date started (UTC)             Description Reference  Amount Fee currency
0         2024-08-04  Www.orange.ro Contul-m       NaN -212.65          RON
1         2024-08-05     To Mihnea Radulescu    Diurna  -30.00          EUR
2         2024-08-04            Lidl Ro 0336       NaN -207.21          RON
3         2024-07-27     To Mihnea Radulescu    Diurna  -70.00          EUR
4         2024-07-27     To Mihnea Radulescu    Diurna  -80.00          EUR

In [25]:
df_rev["Date started (UTC)"] = (
    pd.to_datetime(df_rev["Date started (UTC)"])
    .dt.strftime("%d-%m-%Y")
    .sort_values(ascending=True)
)

In [26]:
filtered_rev = df_rev[~df_rev["Description"].str.contains(r"Mihnea|RON")]
filtered_rev

,Date started (UTC),Description,Reference,Amount,Fee currency
0,04-08-2024,Www.orange.ro Contul-m,NaN,-212.65,RON
2,04-08-2024,Lidl Ro 0336,NaN,-207.21,RON
5,25-07-2024,Ryanair Tsx0,NaN,-386.93,EUR
6,25-07-2024,Rombeer Cringasu Srl,NaN,-199.89,RON
7,23-07-2024,American Restaurant Sy,NaN,-110.00,RON
8,22-07-2024,To VAMADI EURO FINANCE SRL,VEF-799,-500.00,RON
9,22-07-2024,To VAMADI HUMAN RESOURCES S.R.L.,VHR-4589,-50.00,RON
11,20-07-2024,Le Lodge,NaN,-117.00,EUR
13,16-07-2024,Dedeman Blejoi W88-4,NaN,-29.18,EUR
14,14-07-2024,Intermarche Namur,NaN,-23.90,EUR
16,13-07-2024,Action 2517,NaN,-11.21,EUR
18,10-07-2024,Intermarche Jambes,NaN,-52.11,EUR
19,10-07-2024,Q8 104978 Jambes O,NaN,-19.45,EUR
20,10-07-2024,Action 2556,NaN,-1.99,EUR
21,10-07-2024,To BT LEASING TRANSILVANIA IFN SA,74241190017253529,-681.87,RON
22,10-07-2024,To BT LEASING TRANSILVANIA IFN SA,74241190017253529,-2755.66,RON
24,08-07-2024,Uber * Eats Pending,NaN,-25.90,EUR
25,09-07-2024,Restaurant Ceasu Rau,NaN,-37.55,EUR
27,08-07-2024,Www.orange.ro Contul-m,NaN,-40.67,EUR
28,08-07-2024,To Centrul Medical Unirea SRL,RMBU 1481268,-64.86,EUR
29,05-07-2024,Cash at Atm Bucuresti Rossetti,NaN,-40.21,EUR
30,05-07-2024,Cash at Atm Bucuresti Rossetti,NaN,-40.21,EUR

In [27]:
filtered_rev = filtered_rev.rename(columns={
    'Date started (UTC)': 'Payment Date',
    'Description': 'Merchant',
    'Reference': 'Description',
    'Amount': 'Debit',
    'Fee currency': 'Currency'
})

filtered_rev["Account"]= "Rev Business"
filtered_rev['Payment Date'] = pd.to_datetime(filtered_rev['Payment Date'], format='%d-%m-%Y')



filtered_rev.head()

,Payment Date,Merchant,Description,Debit,Currency,Account
0,2024-08-04,Www.orange.ro Contul-m,NaN,-212.65,RON,Rev Business
2,2024-08-04,Lidl Ro 0336,NaN,-207.21,RON,Rev Business
5,2024-07-25,Ryanair Tsx0,NaN,-386.93,EUR,Rev Business
6,2024-07-25,Rombeer Cringasu Srl,NaN,-199.89,RON,Rev Business
7,2024-07-23,American Restaurant Sy,NaN,-110.00,RON,Rev Business

In [29]:

filtered_rev.to_csv('/home/mihnearad/Development/BankingInfo-Parse-Script/.data/filtered/filtered_revbus.csv',index=False)